name: Deploy to Heroku (Express App)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Heroku Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Echo tag for debugging
        run: echo "registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web"

      - name: Build and push to Heroku Container Registry
        uses: docker/build-push-action@v5
        with:
          context: ./express-app
          push: true
          tags: registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Release app on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:release web --app $HEROKU_APP_NAME
